info:
  app:
    description: More description
    name: Agencia de Viajes
    version: 1.0
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
        
server:
  port: 9090
  
spring:
    datasource:
      url: jdbc:mysql://localhost:3306/desarrollodesoft
      username: root
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
            
#spring:
  #jpa:
    #database: POSTGRESQL
    #hibernate.ddl-auto: create-drop
    #show-sql: true
    #generate-ddl: true
    #hibernate:
#     ddl-auto: create     

 # datasource:
    #platform: postgres
  #  driverClassName: org.postgresql.Driver
   # url: jdbc:postgresql://localhost:5432/spring-boot-postgres-db
    #username: postgres
    #password: postgres
    #hikari:
      #connection-init-sql: postgres
   #   maximumPoolSize: 5
